/control/verbose 2
/control/saveHistory
/run/verbose 2
/run/initialize
/vis/open OGL
/vis/drawVolume
/vis/viewer/flush
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
/vis/scene/add/trajectories rich
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/scene/endOfEventAction accumulate
/vis/scene/endOfEventAction accumulate 1000
/vis/verbose warnings
/run/beamOn 10
exit
